version: 0.2
phases:
   install:
      commands:
        - echo "Installing nginx"
        - sudo apt update && sudo apt upgrade -y
        - sudo apt install nginx -y
   build:
      commands:
        - echo "buid started"
        - copy index.html /var/www/html/
   post_build: 
      commands:
        - echo "build successfully done"
artifacts:
  files:
    - /var/www/html/index.html

